### ISSUE TITLE
New currency (Alexander Praetorius and Faircoin?)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#2]
Inspired by this email and some thoughts with @serapath before:

>Hi

>I'd like to present this site to the espacio del inmigrante in Raval, Barcelona and I'd like to find out if you know about legal issues in Spain to do with right to work even when volunteering, and I'd like to have copies of your info on this project in Spanish, Arabic and Wolof if you have any. I work in two related cooperatives, the CIC and Fair.Coop, where we promote alternate currencies, and I wonder if more of a foundation of solid support than an occasional meal in return for work can be reached using these. In particular, I'm trying to see how to get people of various skills to join rural projects requiring a lot of specialised work, where we expect internal community economies to be gift oriented, so allowing the group to work, have a secure home, and not go against any laws. The alt currency thing might tie in with local projects like #ciutatrefugi where the local govt is both supporting refugees being welcomed into homes, and starting an alt currency at the same time. If refugees could work using these more official currencies, I think the benefit would be a lot greater.

>Thanks,

>Ale

**Comment by serapath** [comment]
<3

**Comment by ninabreznik** [comment]
Guys at Fair.coop shared their thread on this issue https://fair.coop/groups/global-south-community/forum/topic/refugees-coop-collaborative-plan-for-helping-them-to-arrive-safe-and-sound/

**Comment by ninabreznik** [comment]
I just read checked this link more thoroughly and saw it's more about housing that about "new monetary/currency" thing...

**Comment by ninabreznik** [comment]
Well, I would like to find a way how to help refugees work legally as soon as possible. Lots of them have to wait for papers too long, or they have papers in one country and when they move around EU, they can't work in another country. So, what do we know about other currencies. How do they work (in the light of people having no work allowance, no company (self-employment), no freelance status...).

**Comment by serapath** [comment]
I have little experience but i found some interesting projects, even though I'm sure there are many more. If you know more people who would like to explore this space or already know it, that would be great.

The projects:
* https://github.com/comcomist/CommunalCoin
* https://github.com/comcomist/iiaom

**Comment by skoria** [comment]
Hi! 

Nice to connect. To explain the first message better, I was just trying to get some info I could send on initially, although I'll encourage people to try the website at the space where I volunteer sometimes here in my neighbourhood, called Espacio del Inmigrante. But I also work at fair.coop which has a global scope, and the Catalan Integral Cooperative (cooperativa.cat) which is local to the catalan region. 

This is why I was proposing looking into how to provide funding for things like the housing project, although as more countries go online on our network we could concievably use it to fund groups like the #marchofhope of refugees currently going from turkey to austria. 

So I guess where faircoop is concerned at this point it's about the idea of linking to an alternate currency and the systems and applications it uses, as a platform for exchanges between geographically distant people for work within a project or space. So that can have many applications and the easiest thing that comes to mind is to add the ability to pay people in faircoin, or other online payment forms like flattr, for the work they do on refugeeswork.

A more advanced thing would be to crowdfund a space centred project that was open to refugees (the problem with most projects is they are officially NOT), for housing or work purposes,  where people could donate towards it either by going there and helping or by just giving donations using local or global alt currencies. 

Hope we can exchange some info on faircoop and faircoin, discuss more, and explain the whole system behind it that we are setting up currently. In general I think the link between the needs of refugees and the possibilities offered by the alternative, sharing or collaborative/circular or as we like to call it, integral economy. We talk about "integral" or holistic approaches to issues because we try to provide frameworks in which different groups can collaborate and get a work or life related project done, and for us this spans many areas - hence the confusion about wether it's about housing or money: you need money for a house and a house to keep your money.  

More specifically, in a project we mention on that thread - Satoshi Forest, Bitcoin was used as a cryptocurrency allowing donations which started out for food, and then expanded into a project to take over some land and build homes, still supported by bitcoin donations. We have our concerns about bitcoin - it's even more unequal than fiat currencies, and with the assistence-oriented nature of Satoshi forest - which as cooperative workers we find a bit strange. Our idea is not to run the risk of creating ghettoes, but creative spaces where people are accepted and can co-exist. 

What we are proposing then, is to allow for faircoin, and local currencies to finance housing projects that can be open to refugees. The legal issue here is that you need to actually hire people so they can work legally, at least in spain. This is both a boon and a barrier because a work contract means ID cards, residency and a lot better chances of staying .This was the method attempted here in Barcelona a couple of years ago by the now failed Cooperativa Integral Calafrica which was migrant led, and had the main purpose of giving people contracts for recycling work in town. But there was infighting, and the council started an alternate project which competed for members and was much more reduced in scope.. Still, around that time, Fair Coop began, as a way to be able to  exchange and network between groups like our Cooperativa Integral Catalana, who strive to de-grow and seek cooperative and communal forms of life and economies. Other groups around the world do the same but like us are tied to our region and it's laws and needs, Faircoop seeks to give us a way to bypass the international banking system which many times is at the root of the reasons people have to migrate in the first place.

So just suggestions and ideas really, and I hope this explanation makes more sense, and I'd love to ask more people to join in with this thread!

Chat soon,

Ale

**Comment by serapath** [comment]
It's a lot of text, but it's difficult for me to understand what it's all about.

**Lifestyle:**
I personally am not yet, but want to become someone with a location independent income who travels all the time - staying in one place for some months, maybe even years and then move on.
I might rent something or exchange the work I can offer and hopefully I can always find some local projects in a place that i can join and contribute to until i move again.

I guess people have different philosophies about how they want to live their life.

**Collaboration:**
So what i would like to see is a lot of people that work together - that collaborate - and share their work. They co-own or otherwise find fair methods how to share what is being created or earned.

So that's my "high-level" perspective on it.

**Currencies:**
Some "things" i feel being related to a potential solution:

1. radical transparency the way you see it in open source (...like on github) - hopefully more
2. maybe "crypto-contracts" can sometimes or often be a part of a solution - API based economy - so that you can rely on agreements if people you work with change their mind in the future - and you don't need to count on complex laws, lawyers and some "government enforcement mechanisms"
3. I feel - the biggest problem (maybe the source?) is our monetary system - it's old, it's centralised, it's undemocratic even though it's what i personally call the "real democracy" (people vote every day by spending) compared to the "fairytale democracy" where people get a basic unconditional income once in 4 years or something to spend it on a fairly limited amount of options - namely "parties" and "politicians" - so a lot has to be changed here.

**How does `fair coin` work?**
* It's blockchain based, right?
* How are new coins issued? (who decides?)
* Is many `fair coins` will there be - if it's unlimited - how is it regulated?
* Is there a mining mechanism or something similar? How does it work?

**How I imagine the crypto-currency that I'd like to see and use:**
* Coins are on average created or destroyed the whole time based on a rate voted for by participants. (for example choosing the `median` of all votes)
* Has some kind of "inflation tax" that finances a "basic unconditional income" (again using for example the `median` of all votes)
* Proofs identity of participants in some way agreed by participants, so that you cannot create "sock puppets" (maybe using something like: http://namzezam.wikidot.com/blog:12#last-minit-note)

On top of this - there can be all kinds of `crowd-sourcing` mechanisms.

**Comment by serapath** [comment]
Maybe you can take a look at http://groupcurrency.org/

**Comment by skoria** [comment]
Hi! 

I'm sorry but I didn't see this until now! 

It's really hard to explain all this here, and I think the cryptocurrency aspect isn't as interesting as the worldwide cooperation between local nodes aspect. 

There's more info on faircoin at http://fair-coin.org on how it has passed through several mechanisms to replace the unequal mining and minting and now uses POC or proof of cooperation as a basic algorithm for creating new coins. In various ways it seeks to address problems and inequalities that make bitcoin quite an unbalanced ecology. 

On the other hand I don't see all that complexity in having a way to send money overseas and for someone in that overseas place to then be able to spend it in their local alternate currencies. 

For example, the best case scenario of FairCoin use is for example a senegalese migrant here in Europe (for example in the catalan restaurant Terra - http://terra.cooperativa.cat ) who works, for example for a summer at the restaurant, and gains faircoin. Using a connected phone or laptop they can use it here to pay for food and lodging or buy things from other producers that are part of faircoop, or they could convert it to euros or our local currency Ecos, and spend it, but they could also send faircoin home to senegal, where it could be converted to btc or to a local currency and spent, or spent directly in faircoin, if there was already a faircoop node there. This way no-one in the example is using the euro, the dollar, or large money transfer groups, which in some areas makes it possible to work and be paid in these currencies. 

As a group, faircoop is also seeking a legal framework to make this trade legally covered in the whole of the EU. For us, proof of identity and the idea of meeting basic needs (the idea that no "basic income" is needed if needs are already met) is already included in the fact that our projects are based on cooperative work in small local spaces where trust can be high. 

What all this doesn't do is give papers or paperwork. A local NGO called Mescladis, here in Barcelona has a loophole in this sense, where they are able to train homeless or paperless people in restoration and hotel skills, and are able to employ them for a year at their space, and via this employment they have access to much longer stay, and are much more able to apply for work when this year runs out. Ideally places like Terra could also adopt models like this, or simple work together with places like Mescladis, which would lead, I think, to rich connections between places like Catalonia, and Senegal, or other places with strong migratory links as the case may be! In the case of refugeework and sites like this, it would mean being able to accept and send payments in these currencies, which they could retrieve or process to send on, at a local node, or on their own if they like. They might want to send it home, transfer it, cash it out, exchange it with our alternate local currency here, or even save it or learn how to do all this themselves, Currently it's difficult for the average person to understand how to use a cryptocurrency (which basically means you becoming a little bank of your own!), so in the beginning we are trying to use the local node structure so people have somewhere to go to to figure it out. About "crypto-contracts" I advise you look into ethereum which is working a lot in this direction. Hope that helps a bit.. I wish you were all here and we could go for a coffee and talk more :)

**Comment by serapath** [comment]
In the first posting you mention
> ...tied to our region and it's laws and needs, Faircoop seeks to give us a way to bypass the international banking system which many times is at the root of the reasons people have to migrate in the first place.

I completely agree that this is a though problem. Strict laws and their enforcement make it hard to try alternatives.

In your new answer you say:
> I think the cryptocurrency aspect isn't as interesting as the worldwide cooperation between local nodes aspect.

I pretty much think there are some fundamental building blocks to make it happen. I currently assume they might be

##### `identity`
(related to signing and/or encrypting with public/private key infrastructure)
* https://passcard.info/#passcardmore
* https://keybase.io/
* and something like http://proofofindividuality.ml/ to scale it in case the community grows
  * https://github.com/d11e9/poi
* this one looks interesting too: https://github.com/MrChrisJ/World-Citizenship
* and here is another suggestion about proofing identity https://github.com/comcomist/iiaom
  * to understand check: http://guptaoption.com/cheapid/
  * Identity Service Architecture: http://guptaoption.com/4.SIAB-ISA.php

##### `group currency`
which means something that has "baked in" rules that reflect modern values of co-operations
* http://groupcurrency.org/
* http://groupincome.org/

##### `organization shares`
Here i do not have a link, but I'm personally hoping to try out a mechanism in a real business with real people, where a `Task Board` (e.g. something like https://trello.com/ exists) and everyone can propose and/or execute `Tasks`, while those who currently have shares support `Tasks` by paying with their shares. Whenever there is revenue coming in from the outside, it's distributed based on who has how many shares. Thats all there is, everything else is open.
We hope we can find a way so that we do not need to deal with `assets`, by organizing everything as a service, but we are not yet sure if it's possible and even if it is, then how well that would scale.

 ---

There might be more, but those basic infrastructure projects would help alot i think.

**Comment by serapath** [comment]
@comcomist also has a project that might be intersting :-)
http://liquid-unions.wikidot.com/the-opening-borders-project
He has put a lot of thought into this and is helping refugees for a long time already. I will try to invite him to the discussion too :-)

**Comment by serapath** [comment]
I will try to read more about **fair-coins** `proof of cooperation` and make another comment later.

**Comment by serapath** [comment]
i like `As a group, faircoop is also seeking a legal framework to make this trade legally covered in the whole of the EU.` too and if you have some kind of `chat room` (_**IRC** or maybe even **gitter.im**_)? I would love to join and discuss some things more :-)

And finally regarding `crypto contracts` - i'm in contact with an employee from `ethereum` and we brainstorm on a regular basis, but the problem is not so much `ethereum` as it is more the **contract** we would like to see - we still "philosophize" about it, but will probably soon try what i describe above under `organization shares` - so if `fair coop` already has something like that, i'd like to learn about it and will soon read more about `FairCoin` and the algorithm you mentioned :-)

thx.
btw. do you think @comcomist could come to visit one of the organizations you mentioned? I think he really would like to try :-)

**Comment by skoria** [comment]
For IRC you can find people from the faircoop admin pool at #faircoop on freenode. This is a group of people maintaining servers for different faircoop related projects, so just one side of it all, but hopefully you can have a few conversations there.. THe next place is the fairnetwork, which is on the fair.coop site itself - for formal introductions, announcements, and for now - basic ID and membership. The main place where we chat and organise is telegram, and we can add you, also usually it's good if you first join via the fair.coop site or the IRC chat. 

For now, id is mostly established informally as we are quite small but yes I'm sure we'll look into that as the whole thing grows. Still, it's about local networks of democratically run productive groups that operate at regional levels, and just providing a link between them all, so I think the concept of relocalisation will remain, and once we build the platform we'll see how to tie into each regional network. 

As far as contracts, we aren't as concerned with legality according to western law, but legitimacy in terms of agreements between people or groups within a transparent environment where transactions can also be discussed face to face at meetings, or agreed in more generic terms (for example the ithaca or bristol city currencies might decide to be 1:1 or to each one be tied to their local fiat currency). Where we do look into legality is where we can work together for to protect members and their activities and make sure they have security and peace of mind. This is why we are setting up a legal group to work towards coverage and protection at a european level. 

About the agreements between people and groups though, groups like Xctit.cooperativa.cat have come up with ethical measurement systems that they have integrated to a license, which works along the lines of a peer production license, prioritising projects that hit more agreed indicators, also agreed by all in an open assembly. When done by a platform cooperative like CIC, we can then trade these open hardware appropriate tech solutions in other regions, and in their own local currency. But these problems are also still to tackle as we are just setting up the basic structures allowing people to use the currency in a day to day way. Chip Chap have recently begun releasing their new web client as part of a lot of development on their part for example, and now they are looking for a faircoin developer to do the faircoin side of this:  http://web.chip-chap.com

If @comcomist wants to come and visit the cooperativa integral catalana - we have a big network of places and spaces all working democratically and ecologically, across catalunya(they are on the site https://cooperativa.cat ) , and you could try writing to info@cooperativaintegral.cat (I'll probably end up seeing it, but so will lots more people) to ask about that. Faircoop spaces & projects are a lot less in number but equally ethically positive, but also please post a message on our website and come and say hi on the catalan node.
