### ISSUE TITLE
Show User profiles (freelancers/entrepreneurs)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#7]
"I find it fantastic what you have done!!! A suggestion: how about having a category where the refugee tells what he or she can do. What skills he or she has. In this way we can approach from the other side as well. 
For example: Are you a refugee? What skill do you have."

**Comment by Dahie** [comment]
This could also be interesting for recurring jobs. Imaging you worked with somebody before, knowing their skillset, you could be motivated to hire him again, due to your (preferably good) experience for other tasks. In my head I have a taxi service, where you hire your personal driver, cause you get to know him and know his skills.

**Comment by ninabreznik** [comment]
True. I am thinking even in direction of freelance/entrepreneur style profiles. So they can offer their services not just CVs. Remember, we are focusing on people who are not looking for long-terms jobs because they can't (no papers) - so alternative is in free work, freelance and entrepreneurship.
